import { Contact, UserSettings } from "@/types/contact";

// The demo used to be frozen at 2026-06-14, with every date written out in
// full. That aged badly: opened three months later, every contact had rotted
// to Cold and the Network Health score read 11/100 — the opposite of what the
// demo is meant to show, and the tour narration ("66/100, 2 cooling") no
// longer matched what was on screen.
//
// Dates are now offsets from whenever the demo is opened, so it always tells
// the same story: Sarah due today, Marc and Priya overdue, the rest on track.
const DAY_MS = 86_400_000;

function daysFromToday(days: number): string {
  const d = new Date(Date.now() + days * DAY_MS);
  d.setUTCHours(0, 0, 0, 0);
  return d.toISOString();
}

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "demo-sarah",
    firstName: "Sarah",
    lastName: "Jones",
    company: "Tesla",
    role: "Senior Recruiter",
    linkedinUrl: "https://linkedin.com/in/sarah-jones",
    email: "sarah.jones@tesla.com",
    phone: "+1 415 555 0192",
    metAt: "TechCrunch Disrupt 2025",
    importance: "High",
    basePriority: "High",
    currentPriority: "High",
    priorityOverride: false,
    industry: "Technology",
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 30,
    cadenceOverride: false,
    firstContactDate: daysFromToday(-195),
    lastInteractionDate: daysFromToday(-25),
    nextFollowUpDate: daysFromToday(0),
    notes: "Discussed engineering leadership roles opening in Q3. She mentioned they're expanding the ML team. Follow up about positions — she prefers a quick LinkedIn message first.",
    createdAt: daysFromToday(-195),
  },
  {
    id: "demo-marc",
    firstName: "Marc",
    lastName: "Dubois",
    company: "L'Oréal",
    role: "Product Manager",
    linkedinUrl: "https://linkedin.com/in/marc-dubois",
    metAt: "SXSW 2025",
    importance: "Medium",
    basePriority: "Medium",
    currentPriority: "Medium",
    priorityOverride: false,
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 60,
    cadenceOverride: false,
    firstContactDate: daysFromToday(-272),
    lastInteractionDate: daysFromToday(-76),
    nextFollowUpDate: daysFromToday(-3),
    notes: "Building a professional network in beauty-tech. Potential collaboration on consumer insights data. Reach out about the new L'Oréal Tech Incubator program.",
    createdAt: daysFromToday(-272),
  },
  {
    id: "demo-priya",
    firstName: "Priya",
    lastName: "Sharma",
    company: "Sequoia Capital",
    role: "Partner",
    linkedinUrl: "https://linkedin.com/in/priya-sharma",
    metAt: "YC Demo Day Spring 2025",
    importance: "High",
    basePriority: "High",
    currentPriority: "High",
    priorityOverride: false,
    industry: "Venture Capital",
    interests: ["climate tech", "AI governance"],
    connectionStatus: "pipeline",
    initialFollowUpDays: 3,
    followUpCadenceDays: 60,
    cadenceOverride: false,
    firstContactDate: daysFromToday(-206),
    lastInteractionDate: daysFromToday(-74),
    nextFollowUpDate: daysFromToday(-2),
    notes: "Focuses on climate tech and AI governance investments. She mentioned interest in my work on sustainable infrastructure. Strong YC ecosystem connection.",
    createdAt: daysFromToday(-206),
  },
  {
    id: "demo-james",
    firstName: "James",
    lastName: "Okafor",
    company: "Google",
    role: "Staff Engineer",
    linkedinUrl: "https://linkedin.com/in/james-okafor",
    metAt: "Google I/O 2026",
    importance: "Medium",
    basePriority: "Medium",
    currentPriority: "Medium",
    priorityOverride: false,
    industry: "Technology",
    function: "Engineering",
    interests: ["AI", "machine learning"],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 30,
    cadenceOverride: false,
    firstContactDate: daysFromToday(-155),
    lastInteractionDate: daysFromToday(-13),
    nextFollowUpDate: daysFromToday(17),
    notes: "",
    createdAt: daysFromToday(-155),
  },
  {
    id: "demo-alex",
    firstName: "Alex",
    lastName: "Rivera",
    company: "Stripe",
    role: "Head of Growth",
    linkedinUrl: "https://linkedin.com/in/alex-rivera",
    metAt: "Stripe Sessions 2026",
    importance: "Medium",
    basePriority: "Medium",
    currentPriority: "Medium",
    priorityOverride: false,
    industry: "Fintech",
    function: "Growth",
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 30,
    cadenceOverride: false,
    firstContactDate: daysFromToday(-120),
    lastInteractionDate: daysFromToday(-20),
    nextFollowUpDate: daysFromToday(10),
    notes: "",
    createdAt: daysFromToday(-120),
  },
  {
    id: "demo-emma",
    firstName: "Emma",
    lastName: "Chen",
    company: "McKinsey & Company",
    role: "Senior Consultant",
    linkedinUrl: "https://linkedin.com/in/emma-chen",
    metAt: "HBS Alumni Event 2024",
    importance: "High",
    basePriority: "High",
    currentPriority: "High",
    priorityOverride: false,
    industry: "Consulting",
    function: "Strategy",
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 2,
    followUpCadenceDays: 90,
    cadenceOverride: false,
    firstContactDate: daysFromToday(-743),
    lastInteractionDate: daysFromToday(-145),
    nextFollowUpDate: daysFromToday(31),
    notes: "Strategy consultant focused on digital transformation in financial services. Could be valuable for consulting referrals. Last talked at the alumni mixer in January.",
    createdAt: daysFromToday(-743),
  },
  {
    id: "demo-lea",
    firstName: "Léa",
    lastName: "Moreau",
    company: "LVMH",
    role: "Marketing Director",
    linkedinUrl: "https://linkedin.com/in/lea-moreau",
    metAt: "Paris Tech Summit 2024",
    importance: "Low",
    basePriority: "Low",
    currentPriority: "Low",
    priorityOverride: false,
    industry: "Luxury Retail",
    function: "Marketing",
    interests: ["luxury brand innovation", "AI personalisation"],
    connectionStatus: "pipeline",
    initialFollowUpDays: 3,
    followUpCadenceDays: 90,
    cadenceOverride: false,
    firstContactDate: daysFromToday(-651),
    lastInteractionDate: daysFromToday(-155),
    nextFollowUpDate: daysFromToday(36),
    notes: "Leading digital transformation at LVMH. Interested in luxury brand innovation and AI personalisation. Met briefly at the summit keynote.",
    createdAt: daysFromToday(-651),
  },
];

export const DEMO_SETTINGS: UserSettings = {
  autoDowngradeAfterMonths: 12,
  careerStatement: "Product leader with a focus on growth and developer tools",
  careerGoals: [],
  goalTags: [],
  hasSeenTutorial: true,
};

export interface DemoHeadline {
  title: string;
  source: string;
  publishedAt: string;
  url: string;
}

export const TESLA_NEWS: DemoHeadline[] = [
  {
    title: "Tesla Reports Record Q2 2026 Deliveries, Beating Analyst Expectations by 8%",
    source: "Reuters",
    publishedAt: daysFromToday(-2),
    url: "https://www.reuters.com/",
  },
  {
    title: "Tesla's Autonomous Robotaxi Service Expands to 12 New Cities Across North America",
    source: "TechCrunch",
    publishedAt: daysFromToday(-5),
    url: "https://techcrunch.com/",
  },
  {
    title: "Tesla Accelerates Hiring Push for AI and Robotics Engineers Ahead of 2027 Product Cycle",
    source: "Bloomberg",
    publishedAt: daysFromToday(-7),
    url: "https://www.bloomberg.com/",
  },
];
