import { Contact, UserSettings } from "@/types/contact";

// Demo is "frozen" at June 14, 2026
// All dates are relative to that reference point

export const DEMO_CONTACTS: Contact[] = [
  {
    id: "demo-sarah",
    firstName: "Sarah",
    lastName: "Jones",
    company: "Tesla",
    role: "Senior Recruiter",
    linkedinUrl: "https://linkedin.com/in/sarah-jones",
    email: "sarah.jones@tesla.com",
    phone: "+1 415 555 0192",
    metAt: "TechCrunch Disrupt 2025",
    importance: "High",
    basePriority: "High",
    currentPriority: "High",
    priorityOverride: false,
    industry: "Technology",
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 30,
    cadenceOverride: false,
    firstContactDate: "2025-12-01T00:00:00.000Z",
    lastInteractionDate: "2026-05-20T00:00:00.000Z",
    nextFollowUpDate: "2026-06-14T00:00:00.000Z",
    notes: "Discussed engineering leadership roles opening in Q3. She mentioned they're expanding the ML team. Follow up about positions — she prefers a quick LinkedIn message first.",
    createdAt: "2025-12-01T00:00:00.000Z",
  },
  {
    id: "demo-marc",
    firstName: "Marc",
    lastName: "Dubois",
    company: "L'Oréal",
    role: "Product Manager",
    linkedinUrl: "https://linkedin.com/in/marc-dubois",
    metAt: "SXSW 2025",
    importance: "Medium",
    basePriority: "Medium",
    currentPriority: "Medium",
    priorityOverride: false,
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 60,
    cadenceOverride: false,
    firstContactDate: "2025-09-15T00:00:00.000Z",
    lastInteractionDate: "2026-03-30T00:00:00.000Z",
    nextFollowUpDate: "2026-06-11T00:00:00.000Z",
    notes: "Building a professional network in beauty-tech. Potential collaboration on consumer insights data. Reach out about the new L'Oréal Tech Incubator program.",
    createdAt: "2025-09-15T00:00:00.000Z",
  },
  {
    id: "demo-priya",
    firstName: "Priya",
    lastName: "Sharma",
    company: "Sequoia Capital",
    role: "Partner",
    linkedinUrl: "https://linkedin.com/in/priya-sharma",
    metAt: "YC Demo Day Spring 2025",
    importance: "High",
    basePriority: "High",
    currentPriority: "High",
    priorityOverride: false,
    industry: "Venture Capital",
    interests: ["climate tech", "AI governance"],
    connectionStatus: "pipeline",
    initialFollowUpDays: 3,
    followUpCadenceDays: 60,
    cadenceOverride: false,
    firstContactDate: "2025-11-20T00:00:00.000Z",
    lastInteractionDate: "2026-04-01T00:00:00.000Z",
    nextFollowUpDate: "2026-06-12T00:00:00.000Z",
    notes: "Focuses on climate tech and AI governance investments. She mentioned interest in my work on sustainable infrastructure. Strong YC ecosystem connection.",
    createdAt: "2025-11-20T00:00:00.000Z",
  },
  {
    id: "demo-james",
    firstName: "James",
    lastName: "Okafor",
    company: "Google",
    role: "Staff Engineer",
    linkedinUrl: "https://linkedin.com/in/james-okafor",
    metAt: "Google I/O 2026",
    importance: "Medium",
    basePriority: "Medium",
    currentPriority: "Medium",
    priorityOverride: false,
    industry: "Technology",
    function: "Engineering",
    interests: ["AI", "machine learning"],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 30,
    cadenceOverride: false,
    firstContactDate: "2026-01-10T00:00:00.000Z",
    lastInteractionDate: "2026-06-01T00:00:00.000Z",
    nextFollowUpDate: "2026-07-01T00:00:00.000Z",
    notes: "",
    createdAt: "2026-01-10T00:00:00.000Z",
  },
  {
    id: "demo-alex",
    firstName: "Alex",
    lastName: "Rivera",
    company: "Stripe",
    role: "Head of Growth",
    linkedinUrl: "https://linkedin.com/in/alex-rivera",
    metAt: "Stripe Sessions 2026",
    importance: "Medium",
    basePriority: "Medium",
    currentPriority: "Medium",
    priorityOverride: false,
    industry: "Fintech",
    function: "Growth",
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 3,
    followUpCadenceDays: 30,
    cadenceOverride: false,
    firstContactDate: "2026-02-14T00:00:00.000Z",
    lastInteractionDate: "2026-05-25T00:00:00.000Z",
    nextFollowUpDate: "2026-06-24T00:00:00.000Z",
    notes: "",
    createdAt: "2026-02-14T00:00:00.000Z",
  },
  {
    id: "demo-emma",
    firstName: "Emma",
    lastName: "Chen",
    company: "McKinsey & Company",
    role: "Senior Consultant",
    linkedinUrl: "https://linkedin.com/in/emma-chen",
    metAt: "HBS Alumni Event 2024",
    importance: "High",
    basePriority: "High",
    currentPriority: "High",
    priorityOverride: false,
    industry: "Consulting",
    function: "Strategy",
    interests: [],
    connectionStatus: "connected",
    initialFollowUpDays: 2,
    followUpCadenceDays: 90,
    cadenceOverride: false,
    firstContactDate: "2024-06-01T00:00:00.000Z",
    lastInteractionDate: "2026-01-20T00:00:00.000Z",
    nextFollowUpDate: "2026-07-15T00:00:00.000Z",
    notes: "Strategy consultant focused on digital transformation in financial services. Could be valuable for consulting referrals. Last talked at the alumni mixer in January.",
    createdAt: "2024-06-01T00:00:00.000Z",
  },
  {
    id: "demo-lea",
    firstName: "Léa",
    lastName: "Moreau",
    company: "LVMH",
    role: "Marketing Director",
    linkedinUrl: "https://linkedin.com/in/lea-moreau",
    metAt: "Paris Tech Summit 2024",
    importance: "Low",
    basePriority: "Low",
    currentPriority: "Low",
    priorityOverride: false,
    industry: "Luxury Retail",
    function: "Marketing",
    interests: ["luxury brand innovation", "AI personalisation"],
    connectionStatus: "pipeline",
    initialFollowUpDays: 3,
    followUpCadenceDays: 90,
    cadenceOverride: false,
    firstContactDate: "2024-09-01T00:00:00.000Z",
    lastInteractionDate: "2026-01-10T00:00:00.000Z",
    nextFollowUpDate: "2026-07-20T00:00:00.000Z",
    notes: "Leading digital transformation at LVMH. Interested in luxury brand innovation and AI personalisation. Met briefly at the summit keynote.",
    createdAt: "2024-09-01T00:00:00.000Z",
  },
];

export const DEMO_SETTINGS: UserSettings = {
  autoDowngradeAfterMonths: 12,
  careerStatement: "Product leader with a focus on growth and developer tools",
  careerGoals: [],
  goalTags: [],
  hasSeenTutorial: true,
};

export interface DemoHeadline {
  title: string;
  source: string;
  publishedAt: string;
  url: string;
}

export const TESLA_NEWS: DemoHeadline[] = [
  {
    title: "Tesla Reports Record Q2 2026 Deliveries, Beating Analyst Expectations by 8%",
    source: "Reuters",
    publishedAt: "2026-06-12T10:00:00Z",
    url: "https://www.reuters.com/",
  },
  {
    title: "Tesla's Autonomous Robotaxi Service Expands to 12 New Cities Across North America",
    source: "TechCrunch",
    publishedAt: "2026-06-09T14:30:00Z",
    url: "https://techcrunch.com/",
  },
  {
    title: "Tesla Accelerates Hiring Push for AI and Robotics Engineers Ahead of 2027 Product Cycle",
    source: "Bloomberg",
    publishedAt: "2026-06-07T08:00:00Z",
    url: "https://www.bloomberg.com/",
  },
];
